services:
  cabin-parser-db:
    container_name: cabin-parser-db
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: cabin_parser
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: UTC
    ports:
      - 5432:5432
